import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { trpc } from '../../utils/trpc'

import dancecat from '../../../public/dancecat.gif'
import zoomies from '../../../public/zoomies.gif'
import Link from 'next/link'
const Posts: NextPage = () => {
  // const { data, isLoading } = trpc.useQuery([
  //   'example.hello',
  //   { text: ' Michael' },
  // ])

  const { data, isLoading } = trpc.useQuery(['posts.getAllPosts'])

  if (isLoading) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>De.Bug Tech Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- Navbar --> */}
      <nav className="relative w-screen h-40 bg-primary_blue">
        <div className="flex items-center justify-between w-screen h-20 px-8">
          <div className="text-2xl font-semibold text-center text-white">
            De.bug Blog
          </div>
          <div className="text-2xl font-semibold text-center text-white">
            Menu
          </div>
        </div>
      </nav>
      <div className="absolute flex items-center justify-center w-screen overflow-visible top-16">
        <div className="w-auto h-auto">
          <Image objectFit="contain" src={zoomies} alt={'dancecat'} priority />
        </div>
      </div>

      <div className="flex flex-col w-screen h-screen bg-white">
        <div className="relative w-32 h-32 mx-8 my-2 overflow-hidden rounded-full ring-2">
          <Image
            objectFit="cover"
            src={dancecat}
            alt={'dancecat'}
            layout={'fill'}
            priority
          />
        </div>
        <div className="mx-8">
          <h3 className="font-extrabold text-1xl text-primary_blue">
            Post List
          </h3>
          <h1 className="text-3xl font-bold hover:cursor-pointer hover:text-primary_blue">
            {data && data.map((post) => post.title)}
          </h1>
        </div>
        <div className="w-4/5 mx-8 my-4">
          <p> {data && data.map((post) => post.content)}</p>
          <div className="w-32 p-2 font-bold text-center text-white rounded bg-primary_red"></div>
        </div>
      </div>
    </>
  )
}

export default Posts
