import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { trpc } from '../../utils/trpc'
import Link from 'next/link'
import { useRouter } from 'next/router'

const NewPost: NextPage = () => {
  const router = useRouter()
  const { mutate, error } = trpc.useMutation(['posts.createPost'])

  const handleSubmit = () => {
    mutate({
      title: 'Hello World',
      content: 'This is a test post',
    })
  }

  return (
    <>
      <Head>
        <title>De.Bug Tech Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- Navbar --> */}
      <nav className="relative w-screen h-40 bg-primary_blue">
        <div className="flex items-center justify-between w-screen h-20 px-8">
          <div className="text-2xl font-semibold text-center text-white">
            De.bug Blog
          </div>
          <div className="text-2xl font-semibold text-center text-white">
            Menu
          </div>
        </div>
      </nav>

      <div className="flex flex-col w-screen h-screen bg-white">
        <div className="mx-8">
          <h3 className="font-extrabold text-1xl text-primary_blue">
            New Post
          </h3>
        </div>
        <button onClick={handleSubmit}>Add Test post</button>
      </div>
    </>
  )
}

export default NewPost
