import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { trpc } from '../../utils/trpc'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useForm } from 'react-hook-form'
import { CreatePostSchema } from '../../schema/posts.schema'

const NewPost: NextPage = () => {
  const router = useRouter()
  const { mutate, error } = trpc.useMutation(['posts.createPost'])
  const { handleSubmit, register } = useForm<CreatePostSchema>()

  const onSubmit = (values: CreatePostSchema) => {
    mutate(values)
  }

  return (
    <>
      <Head>
        <title>De.Bug Tech Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- Navbar --> */}
      <nav className="relative w-screen h-40 bg-primary_blue">
        <div className="flex items-center justify-between w-screen h-20 px-8">
          <div className="text-2xl font-semibold text-center text-white">
            De.bug Blog
          </div>
          <div className="text-2xl font-semibold text-center text-white">
            Menu
          </div>
        </div>
      </nav>

      <div className="flex flex-col w-screen h-screen bg-white">
        <div className="mx-8">
          <h3 className="font-extrabold text-1xl text-primary_blue">
            New Post
          </h3>
        </div>
        <div className="container justify-center mx-auto">
          <form
            onSubmit={handleSubmit(onSubmit)}
            className="flex flex-col items-center p-10 m-10"
          >
            <input
              type="text"
              placeholder="Title"
              {...register('title')}
              className="w-3/5 p-2 border-t-2 border-gray-500 border-x-2"
            />
            <textarea
              placeholder="Content"
              {...register('content')}
              className="w-3/5 p-2 border-2 border-gray-500"
            />
            <button className="p-4 my-2 text-white rounded-lg bg-primary_blue hover:cursor-pointer">
              Create Post
            </button>
          </form>
        </div>
      </div>
    </>
  )
}

export default NewPost
