import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { trpc } from '../utils/trpc'

import dancecat from '../../public/dancecat.gif'
import zoomies from '../../public/zoomies.gif'
const Home: NextPage = () => {
  const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }])

  return (
    <>
      <Head>
        <title>De.Bug Tech Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- Navbar --> */}
      <nav className="relative w-screen h-40 bg-primary_blue">
        <div className="flex items-center justify-between w-screen h-20 px-8">
          <div className="text-2xl font-semibold text-center text-white">
            De.bug Blog
          </div>
          <div className="text-2xl font-semibold text-center text-white">
            Menu
          </div>
        </div>
      </nav>
      <div className="absolute flex items-center justify-center w-screen overflow-visible top-16">
        <div className="w-auto h-auto">
          <Image objectFit="contain" src={zoomies} alt={'dancecat'} priority />
        </div>
      </div>

      <div className="flex flex-col w-screen h-screen bg-white">
        <div className="relative w-32 h-32 mx-8 my-5 overflow-hidden rounded-full ring-2">
          <Image
            objectFit="cover"
            src={dancecat}
            alt={'dancecat'}
            layout={'fill'}
            priority
          />
        </div>
        <div className="mx-8">
          <h3 className="font-extrabold text-1xl text-primary_blue">
            Policy & Safety
          </h3>
          <h1 className="text-3xl font-bold hover:cursor-pointer hover:text-primary_blue">
            DISCORD TRANSPARENCY REPORT: JANUARY - MARCH 2022
          </h1>
        </div>
        <div className="w-4/5 mx-8 my-4">
          <p>
            We recognize that safety enables people to find belonging. That is
            why safety is one of Discord’s most important priorities and
            investments as a company. Our Engineering, Data, and Product teams
            work with safety principles in mind when building products. Our
            Policy team takes a nuanced and sophisticated approach to developing
            our Community Guidelines and forms strategic partnerships with
            academics, civil society, industry peers, and moderators to advance
            our collective understanding of online safety. Our Trust & Safety
            team works with cutting-edge technology to detect and respond to
            abuse, both proactively and from users, moderators, and trusted
            third party reporters. This expansive effort and commitment to
            safety brings together around 15% of all Discord employees. We’re
            continuously expanding our efforts to help ensure that everyone can
            have a safer experience that allows for belonging on Discord.
            Transparency is one of the core values of our safety work at
            Discord. These Transparency Reports are a way to demonstrate our
            commitment and provide insight into the enormous effort that goes
            into keeping Discord a safe place for all.
          </p>
        </div>
      </div>
    </>
  )
}

export default Home
